app:
  secretKey: secret
  clientURL: "http://localhost:3000"

database:
  host: localhost
  port: 5432
  dbName: bn_db
  username: root
  password: secret
  sslMode: disable
  debug: true

httpServer:
  host: localhost
  port: 8080
  debug: true

oAuth2:
  github:
    clientID: "<GITHUB_CLIENT_ID>"
    clientSecret: "<GITHUB_CLIENT_SECRET>"
    redirectURL: "http://localhost:8080/api/v1/oauth2/github/callback"
