name: Build

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: login to github docker registry
      uses: docker/login-action@v1.14.1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: publish docker image to registry
      env:
        COMMIT_SHA: ${{ github.sha }}
        REPO_REGISTRY: ghcr.io/${{ github.repository_owner }}/batnoter
      run: |
        docker build \
          -t $REPO_REGISTRY/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/} \
          -t $REPO_REGISTRY/${GITHUB_REPOSITORY#*/}:$COMMIT_SHA \
          -t $REPO_REGISTRY/${GITHUB_REPOSITORY#*/}:latest .
        docker push -a $REPO_REGISTRY/${GITHUB_REPOSITORY#*/}
