name: Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'https://batnoter.com'

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: login to heroku docker registry
      uses: docker/login-action@v1.14.1
      with:
        registry: registry.heroku.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.HEROKU_API_KEY }}

    - name: deploy to heroku
      env:
        HEROKU_APP_NAME: batnoter
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:push web -a $HEROKU_APP_NAME
        heroku container:release web -a $HEROKU_APP_NAME
        heroku releases --json -n 1 -a $HEROKU_APP_NAME | grep '"succeeded"'
